# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SportsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SportsApp
  pod 'Kingfisher', '~> 6.0'
  pod 'Alamofire', '~> 5.0.0-beta.6'
  pod 'lottie-ios'

  target 'SportsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SportsAppUITests' do
    # Pods for testing
  end

end
